
# plugins:
# - jekyll-remote-theme
  
# theme: vue-jekyll-theme
# remote_theme: LukasChen/jekyllVue
# JorisKok/vue-jekyll-theme

theme: jekyll-theme-cayman

nav:
- page: Header One
  permalink: #header-one

- page: Header Two
  permalink: #header-two
